changed settings, created new branch
stevenpatricklang/Sidekick_Horse pull request #12
Opened 2022-11-24 14:11 UTC by stevenpatricklang

2022-11-28 16:23 UTC, ChristianBorn requested changes
There is one code smell:
[1 Code Smell](https://sonarcloud.io/project/issues?id=stevenpatricklang-1_Sidekick_Horse_frontend&pullRequest=12&resolved=false&types=CODE_SMELL)

2022-11-28 16:30 UTC, chris-yooo requested changes

2022-11-28 16:30 UTC, chris-yooo commented on backend/src/main/java/sidekickhorse/backend/member/NewMember.java
>          @Email
maybe here notnull and notempty again :)

2022-11-28 16:30 UTC, chris-yooo commented on frontend/src/App.css
> +
delete this file

2022-11-28 16:30 UTC, chris-yooo commented on frontend/src/member/AddMemberForm.tsx
> +                    <Icon icon="mdi:register" width="14"/> Add Member</StyledButton>
please put here within the icon    inline="true"

2022-11-28 16:30 UTC, chris-yooo commented on frontend/src/member/MemberModal.tsx
> +    const handleNewFirstName = (event: any) => {
you can write this short and cool directly in line where you need the handle

2022-11-28 16:49 UTC, ChristianBorn commented on backend/src/main/java/sidekickhorse/backend/member/NewMember.java
> +        @NotBlank @NotEmpty @NotNull
@NotEmpty can be deleted, @NotBlank and @NotNull are sufficient
@NotEmpty is used for arrays

2022-11-28 16:49 UTC, ChristianBorn commented on backend/src/test/java/sidekickhorse/backend/member/MemberIntegrationTest.java
> +                                """.replace("<id>", member.id()))))
I don't see why this json is so long and consists of two objects?

2022-11-28 16:49 UTC, ChristianBorn commented on backend/src/test/java/sidekickhorse/backend/member/MemberIntegrationTest.java
> +                        """.replace("<id>", member.id())));
Same as my last comment

2022-11-28 16:49 UTC, ChristianBorn commented on backend/src/test/java/sidekickhorse/backend/member/MemberIntegrationTest.java
> +                .andExpect(status().isBadRequest());
Consider using 404 NOT FOUND

2022-11-28 16:49 UTC, ChristianBorn commented on frontend/src/member/AddMemberForm.tsx
>      const [messageStatus, setMessageStatus] = useState('')
Consider using double quotes instead of single quotes for the sake of consistency

2022-11-28 16:49 UTC, ChristianBorn commented on frontend/src/member/MemberBoard.tsx
> +                    <MemberModal closeModal={closeModal}
I think you could pass the handleEdit method to closeModal because it inverts the value of editModal.
Would make the closeModal method obsolete

2022-11-28 16:49 UTC, ChristianBorn commented on frontend/src/member/MemberModal.tsx
> +    const [newEmail, setEmail] = useState("")
Could be shortened by using a useState that takes a whole member-object.
Would also make the all the handleXyz obsolete. You can have a look here: https://github.com/ChristianBorn/Capstone/blob/master/frontend/src/stock/EditItemModal.tsx

2022-11-28 16:49 UTC, ChristianBorn commented on frontend/src/member/MemberModal.tsx
> +                <StyledButton onClick={props.closeModal}>Update</StyledButton>
I think you wanted the updateMember function as onClick action here?

2022-11-29 08:10 UTC, chris-yooo approved these changes

2022-11-29 08:41 UTC, ChristianBorn approved these changes

2022-11-29 08:42 UTC, merged