Feature GET
stevenpatricklang/Sidekick_Horse pull request #7
Opened 2022-11-22 16:52 UTC by stevenpatricklang

2022-11-23 14:19 UTC, Kreyno93 requested changes
please delete the unnecessary things which does not be needed for the "get" feature.
delete,update etc.
=> Vertical Slice

2022-11-23 14:19 UTC, Kreyno93 commented on frontend/src/member/MemberPage.tsx
> +             <NavLink to="/add/members">Add MemberPage</NavLink></StyledButton>
Maybe change name to 

`<NavLink to="/add/members">Add Member</NavLink></StyledButton>`

2022-11-23 14:19 UTC, Kreyno93 commented on frontend/src/member/MemberPage.tsx
> +             <NavLink to="/add/members">Add MemberPage</NavLink></StyledButton>
and change the routing to 

/members/add

2022-11-23 14:19 UTC, Kreyno93 commented on frontend/src/pages/About.tsx
> +            <StyledButton><NavLink to="/add/members">Go to the Add Members page</NavLink></StyledButton>
same here : /members/add && /members/list etc.

2022-11-23 14:21 UTC, bartfastiel requested changes

2022-11-23 14:21 UTC, bartfastiel commented on frontend/src/member/MemberBoard.tsx
> +                    <StyledButton onClick={deleteMember}>delete</StyledButton>
Bitte den delete-Button noch raus nehmen (inkl. Axios-Call, etc.) - es gibt ja noch keinen Delete-Endpunkt im Backend

2022-11-23 14:21 UTC, bartfastiel commented on frontend/src/member/MemberPage.tsx
> +             <NavLink to="/add/members">Add MemberPage</NavLink></StyledButton>
Bitte die Formulierungen überarbeiten. "Page" ist vielleicht nicht allen Anwender*innen geläufig.

```suggestion
             <NavLink to="/add/members">Add member</NavLink></StyledButton>
```

2022-11-23 14:21 UTC, bartfastiel commented on frontend/src/member/MemberBoard.tsx
> +                    <StyledButton onClick={handleEdit}>Edit Member</StyledButton>
Bitte den edit-Button noch raus nehmen (inkl. Axios-Call, etc.) - es gibt ja noch keinen PUT-Endpunkt im Backend

2022-11-23 14:21 UTC, bartfastiel commented on backend/src/test/java/sidekickhorse/backend/member/MemberServiceTest.java
> +        Member member = new Member ("Steven", "Lang", "Kirchweg 6", "86856", "Hiltenfingen", "steven@gmail.com", "1");
Falls das Deine richtige Adresse ist, empfehle ich Dir, sie (hier im Code) zu ändern ;)

2022-11-23 14:21 UTC, bartfastiel commented on backend/src/test/java/sidekickhorse/backend/member/MemberIntegrationTest.java
> +    @DirtiesContext
Bei diesem Test wird aktuell kein Zustand verändert. Die Zeile kannst (und solltest) Du aus meiner Sicht entfernen.

2022-11-23 14:21 UTC, bartfastiel commented on frontend/src/App.tsx
> +        <Route path="/list/members" element={<MemberPage />}/>
Im Frontend gibt es zwar bei den Pfaden nicht so klare Richtlinien wie mit REST im Backend, aber nichts desto trotz würde ich eine Struktur bevorzugen, bei der allgemeineres vorn und konkreteres hinten im Pfad steht.

```suggestion
        <Route path="/members/add" element={<AddMemberForm />}/>
        <Route path="/members/list" element={<MemberPage />}/>
```

2022-11-23 14:21 UTC, bartfastiel commented on frontend/src/member/MemberBoard.tsx
> +                    setMessageStatus(' New Member ' + props.member.firstName + " " + props.member.lastName + ' successfully deleted.');
Die Delete-Funktion kann ja eventuell sowieso vorerst raus (weil es dafür noch kein Backend gibt). Unabhängig davon würde hier aber die Formulierung noch nicht passen (` New Member ... deleted` - entweder neu oder deleted, aber beides passt nicht, stimmt's?)

2022-11-23 15:05 UTC, stevenpatricklang commented on frontend/src/member/MemberBoard.tsx
> +                    setMessageStatus(' New Member ' + props.member.firstName + " " + props.member.lastName + ' successfully deleted.');
vielen Dank für euer Feedback. Änderungen habe ich gerade gemacht

2022-11-24 08:25 UTC, bartfastiel requested changes

2022-11-24 08:25 UTC, bartfastiel commented on backend/src/test/java/sidekickhorse/backend/member/MemberIntegrationTest.java
> +    @Test
(Leerzeile)

2022-11-24 08:25 UTC, bartfastiel commented on backend/src/test/java/sidekickhorse/backend/member/MemberServiceTest.java
> +        List<Member> actual = memberRepository.findAll();
Achtung: Den Service testen, nicht das gemockte Repo

2022-11-24 08:25 UTC, bartfastiel commented on backend/src/test/java/sidekickhorse/backend/member/MemberServiceTest.java
> +        members.add(member);
```suggestion
        List<Member> members = List.of(
            new Member ("Steven", "Lang", "Kirchweg 6", "86856", "Hiltenfingen", "horsty@gmail.com", "1")
        );
```

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/member/MemberBoard.tsx
> +}
Bitte raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/member/MemberBoard.tsx
> +    let editModal;
Bitte raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/member/MemberBoard.tsx
> +                {messageStatus && <StyledDeleteMessage>{messageStatus}</StyledDeleteMessage>}
Delete Message bitte raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/member/MemberBoard.tsx
> +`;
Bitte raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/member/MemberBoard.tsx
> +                </StyledDiv>
Bitte raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/member/MemberBoard.tsx
> +
Bitte raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/member/MemberBoard.tsx
> +    let messageStatus;
Bitte raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/member/MemberBoard.tsx
> +                    Street: {props.member.street}
Wolltest Du raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/member/MemberModal.tsx
> +`;
Bitte raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/member/MemberPage.tsx
> +         <p> </p>
Bitte raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/member/MemberPage.tsx
> +         <p> </p>
Bitte raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/pages/About.tsx
> +            <p> </p>
Bitte raus nehmen

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/pages/About.tsx
> +            </StyledDiv>
Vereinen zu einem einzelnen Element, css statt `width=850`, statt width in px lieber z.B. `80vw` für 80% der Bildschirmbreite

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/pages/About.tsx
> +           <StyledButton><NavLink to="/members/add">Add Member</NavLink></StyledButton>
Auto formatting

2022-11-24 08:25 UTC, bartfastiel commented on frontend/src/pages/About.tsx
> +            <p> </p>
Bitte raus nehmen

2022-11-24 13:15 UTC, ZeshanShahid79 commented on frontend/src/member/MemberModal.tsx
> +export default MemberModal;
add a new line at the end pls

2022-11-24 13:15 UTC, ZeshanShahid79 commented on frontend/src/member/MemberPage.tsx
> +`;
same here pls

2022-11-24 13:16 UTC, ZeshanShahid79 reviewed
change as commented and i think it should be fine :D

2022-11-24 13:20 UTC, ZeshanShahid79 approved these changes
after u change as suggested in my comments it should be done

2022-11-24 13:24 UTC, closed without merging

2022-11-24 13:25 UTC, stevenpatricklang commented
reviewer is not available